### ISSUE TITLE
ThemeManager is not a constructor

### ISSUE THREAD

**Issue by russjr08** [banderson/generator-flux-react#40]
Hi,

I'm getting the following error while using the default template for MaterialUI

    TypeError: _materialUi.Styles.ThemeManager is not a constructor

It appears to be at index.js at line 41907 (column 20).

**Comment by blairanderson** [comment]
i think you're in the wrong repo.

**Comment by russjr08** [comment]
No, it's an issue with how the default template is setup. I don't have the material-ui project anymore, but I believe in one of the default files (Do a search for ThemeManager), it's being treated as a constructor, when it should be more like:

    var manager = the.namespace.ThemeManager
(without the 'new' keyword and ()  )

**Comment by banderson** [comment]
@russjr08 I see what you mean, it turns out Material UI released a breaking change to this API just a couple days before you opened this issue :(  https://github.com/callemall/material-ui/releases/tag/v0.12.0

I updated the API to be compatible with 0.12 and then I pinned the installation to that version to hopefully prevent future breakages of this type. 

Thanks for reporting, let me know if you run into any other issues.

Your changes are included in the just-published 0.4.5 version.
